### ISSUE TITLE
Having multiple instances with different labels/configs

### ISSUE THREAD

**Issue by thinklinux** [paul-milne/zap-loki#2]
I'm trying to have couple of different instances of zap-loki with different labels. Is that possible? Right now it gives me this error:

```
sink factory already registered for scheme "loki"
```

As far as I can see in the code lokiSinkKey is hardcoded. Which means that I can't init multiple loggers with different config? Am I missing something?

Thank you!

**Comment by paul-milne** [comment]
yeah you are 100% correct. This was a use case not thought of but it is now configurable via the config and will default to "loki" if no SinkKey is provided.
